language: java
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - mvn --non-recursive scm:checkout -Dmodule.name=JSON-java
  - mvn --non-recursive scm:checkout -Dmodule.name=morph
  - mvn --non-recursive scm:checkout -Dmodule.name=extractors
  - mvn --non-recursive scm:checkout -Dmodule.name=entity-extractor
  - mvn --non-recursive scm:checkout -Dmodule.name=graph-alignment
  - mvn --non-recursive scm:checkout -Dmodule.name=document-service-client-java
  - mvn clean install -Dmaven.test.skip=true
  - cd stucco-topology
after_success:
  - wget https://raw.githubusercontent.com/stucco/test/master/rerun-test.sh
  - chmod a+x ./rerun-test.sh
  - ./rerun-test.sh