language: java
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - mvn --non-recursive scm:checkout -Dmodule.name=document-service-client-java
  - mvn --non-recursive scm:checkout -Dmodule.name=STIXExtractors
  - mvn --non-recursive scm:checkout -Dmodule.name=entity-extractor -DscmVersion=STIX -DscmVersionType=branch
  - cd entity-extractor
  - mvn -e clean install -Dmaven.test.skip=true
  - cd ..
  - mvn --non-recursive scm:checkout -Dmodule.name=relation-extractor -DscmVersion=STIX -DscmVersionType=branch
  - cd relation-extractor
  - mvn -e clean install -Dmaven.test.skip=true
  - cd ..
  - mvn -q --non-recursive scm:checkout -Dmodule.name=graph-db-connection -DscmVersion=feature/bulkLoad -DscmVersionType=branch
  - cd graph-db-connection
  - mvn -e clean install -Dmaven.test.skip=true
  - cd ..
  - mvn -q --non-recursive scm:checkout -Dmodule.name=graph-alignment -DscmVersion=feature/bulkLoad -DscmVersionType=branch
  - cd graph-alignment
  - mvn -e clean install -Dmaven.test.skip=true
  - cd ..
  - mvn clean install -Dmaven.test.skip=true
  - cd streaming-processor
after_success:
  - wget https://raw.githubusercontent.com/stucco/test/master/rerun-test.sh
  - chmod a+x ./rerun-test.sh
  - ./rerun-test.sh
notifications:
  slack: sava:lB0VBcWKom3VNlr126hyI04E
