language: java
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - mvn --non-recursive scm:checkout -Dmodule.name=JSON-java
  - mvn --non-recursive scm:checkout -Dmodule.name=morph
  - mvn --non-recursive scm:checkout -Dmodule.name=extractors
  - mvn --non-recursive scm:checkout -Dmodule.name=entity-extractor
  - mvn clean install
  - cd stucco-topology
