language: java
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - mvn -q --non-recursive scm:checkout -Dmodule.name=rexster-client-java
  - cd rexster-client-java
  - mvn -e clean install -Dmaven.test.skip=true
  - cd ..
  - mvn --non-recursive scm:checkout -Dmodule.name=JSON-java
  - mvn --non-recursive scm:checkout -Dmodule.name=morph
  - mvn --non-recursive scm:checkout -Dmodule.name=html-extractor
  - mvn --non-recursive scm:checkout -Dmodule.name=extractors
  - mvn --non-recursive scm:checkout -Dmodule.name=entity-extractor
  - mvn --non-recursive scm:checkout -Dmodule.name=relation-extractor
  - mvn --non-recursive scm:checkout -Dmodule.name=document-service-client-java
  - mvn --non-recursive scm:checkout -Dmodule.name=graph-alignment
  - mvn clean install -Dmaven.test.skip=true
  - cd streaming-processor
after_success:
  - wget https://raw.githubusercontent.com/stucco/test/master/rerun-test.sh
  - chmod a+x ./rerun-test.sh
  - ./rerun-test.sh
notifications:
  slack: sava:lB0VBcWKom3VNlr126hyI04E