storm:
  debug: no
  workers: 3

instances:
  rabbitmq: 2
  uuid: 2
  route: 2

  parse: 5

  extract: 5
  concept: 5
  relation: 5

  document: 2
  graph: 10

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  vhost: /
  queue:
    name: stucco
    durable: no
    exclusive: no
    autoDelete: no
