structured_data:
  exchange: stucco
  host: localhost
  port: 5672
  username: stucco
  password: stucco
  queue: stucco-in-structured
  emptyQueueSleepTime: 90000
  persistent: true
  bindings: 
      - stucco.in.structured.#

unstructured_data:
  exchange: stucco
  host: localhost
  port: 5672
  username: stucco
  password: stucco
  queue: stucco-in-unstructured
  emptyQueueSleepTime: 90000
  persistent: true
  bindings:
      - stucco.in.unstructured.#
  serialObjectDir: ../docs

document_service:
  host: localhost
  port: 8118
  
