storm:
  debug: no
  workers: 1

instances:
  rabbitmq: 1
  uuid: 1
  route: 1

  parse: 1

  extract: 1
  concept: 1
  relation: 1

  document: 1
  graph: 1

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  vhost: /
  queue:
    name: stucco
    durable: no
    exclusive: no
    autoDelete: no
