structured_data:
  exchange: stucco
  host: localhost
  port: 5672
  username: guest
  password: guest
  queue: stucco-in-structured
  emptyQueueSleepTime: 90000
  bindings: 
      - stucco.in.structured.#

unstructured_data:
  exchange: stucco
  host: localhost
  port: 5672
  username: guest
  password: guest
  queue: stucco-in-unstructured
  emptyQueueSleepTime: 90000
  bindings:
      - stucco.in.unstructured.#

document_service:
  host: localhost
  port: 8000
  